### ISSUE TITLE
command method: management of asynchronicity

### ISSUE THREAD

**Issue by mcoulont** [crazymerlyn/uci-rs#1]
Hello

I've noticed while using your code that above a certain depth the results of the latest depths didn't appear in the output of the `command` method.

Looking at your code, I've seen that you just waited for 100 milliseconds before returning the output of the command.

Is it possible in some way to use tour crate to get the analysis reports for bigger depths?

**Comment by crazymerlyn** [comment]
There's no difference between an engine thinking and an engine not responding forever, so I have to chose some time to stop and consider the operation done. Added a new function to make the duration configurable in 549408ae76f85575926510f00a678bff6c4cbaab.

**Comment by mcoulont** [comment]
OK but you could wait for the expected last line returned by the engine (for a certain amount of time, say your configurable one) and then return the whole.

**Comment by crazymerlyn** [comment]
Sounds reasonable. Added a function to wait for a specified prefix in ba46fd29d4c08ba95c332f3e1d9a59654c795401.

**Comment by mcoulont** [comment]
It's working. Thank you very much.
